language: elixir
#elixir:
#  - 1.3.3
#  - 1.3.4
#  - 1.4.0-rc.0
#  - 1.4.0
#  - 1.4.1
#  - 1.4.2
#  - 1.4.4
#  - 1.4.5
#otp_release:
#  - 18.0
#  - 18.1
#  - 19.0
#  - 19.1
#  - 19.2
#  - 19.3
matrix:
  include:
    #    - otp_release: 18.0
    #      elixir: 1.4.0-rc.1
    #    - otp_release: 18.1
    #      elixir: 1.4.0-rc.1
    #    - otp_release: 20.0
    #      elixir: 1.4.5
    #    - otp_release: 18.0
    #      elixir: 1.5.0
    #    - otp_release: 18.1
    #      elixir: 1.5.0
    #    - otp_release: 19.0
    #      elixir: 1.5.0
    #    - otp_release: 19.1
    #      elixir: 1.5.0
    #    - otp_release: 19.2
    #      elixir: 1.5.0
    #    - otp_release: 19.3
    #      elixir: 1.5.0
    #    - otp_release: 20.0
    #      elixir: 1.5.0
    #    - otp_release: 18.0
    #      elixir: 1.5.1
    #    - otp_release: 18.1
    #      elixir: 1.5.1
    #    - otp_release: 19.0
    #      elixir: 1.5.1
    #    - otp_release: 19.1
    #      elixir: 1.5.1
    #    - otp_release: 19.2
    #      elixir: 1.5.1
    #    - otp_release: 19.3
    #      elixir: 1.5.1
    #    - otp_release: 20.0
    #      elixir: 1.5.1
    - otp_release: 20.0
      elixir: 1.6.4
addons:
  artifacts:
    debug: true
    paths:
      - $(ls plts/*.plt)
    working_dir: plts
    target_paths:
      - travis_elixir_plts
before_install:
  - sudo service --status-all
  - sudo free -m -t
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop
  - sudo /etc/init.d/redis-server stop
  - sudo free -m -t
before_script:
  - export PATH=`pwd`/elixir/bin:$PATH
  - git clone https://github.com/jeremyjh/dialyxir.git
  - cd dialyxir
  - MIX_ENV=prod mix do compile, archive.build
  - MIX_ENV=prod mix archive.install --force
  - cd ..
script:
  - MIX_ENV=test travis_wait 30 mix dialyzer --plt
after_failure:
  - sudo free -m -t
  - sudo dmesg
